# Boek configuratie
# https://jupyterbook.org/customize/config.html

title: Creatief Programmeren met Processing

# Auteur is verplicht, maar wordt voor de syllabus site automatisch aangepast op
# basis van de commitgeschiedenis.
author: Q-highschool

# Standaard worden alleen bestanden die in _toc.yml genoemd worden "gecompileerd"
only_build_toc_files: true

# Alle code in een notebook wordt opnieuw uitgevoerd tijdens compilatie.
# TODO: Pas dit aan naar wat handig is in jouw context, zie
# https://jupyterbook.org/content/execute.html. Voor syllabi zonder code zet
# execute_notebooks op "off" (inclusief quotes!)
execute:
  execute_notebooks: "off"

# Configuratie voor de MyST Markdown parser, met een aantal handige extensies
# standaard aangezet. Zie https://myst-parser.readthedocs.io/en/latest/syntax/optional.html
parse:
  myst_enable_extensions:
    - colon_fence # Zodat ook ::: gebruikt kan worden voor admonitions
    - deflist # <dl> definition list syntax zoals in Pandoc
    - dollarmath # Schrijf LaTeX formules tussen $ (inline) of $$ (blok)
    - fieldlist # Een soort tabel van eigenschappen
    - html_image # Sta <img /> elementen toe voor afbeeldingen
    - linkify # Maak automatisch links van teksten die op een link lijken
    - replacements # Vervang (c) door een copyright symbool etc.
    - smartquotes # Vervang ' en " door echte, schuine quotes (pas op met code!)
    - substitution # Vervang {{ key }} in teksten met een waarde uit deze configuratie
    - tasklist # Takenlijst zoals in GitHub Flavored Markdown (- [ ] Dit is een taak)

sphinx:
  # Extensions voor speciale Markdown blokken via Sphinx, bijvoorbeeld voor
  # opdrachten (zie de link hieronder). Voeg ook de bijbehorende Python packages
  # toe aan requirements.txt, als je hier een extensie toevoegt!
  extra_extensions:
    - sphinx_exercise # https://ebp-sphinx-exercise.readthedocs.io/en/latest/syntax.html
    - sphinx_togglebutton
  recursive_update: true
  config:
    language: nl
    # Vertaling van "Exercise" voor de exercise extensie. Werkt alleen voor
    # genummerde oefeningen en iets vergelijkbaars is helaas niet mogelijk voor
    # "Solution to".
    # We wachten op https://github.com/executablebooks/sphinx-exercise/issues/13
    numfig_format:
      exercise: "Oefening %s"
    togglebutton_hint: "Klik hier voor een hint"
    togglebutton_hint_hide: "Klik om de hint te verbergen"
    # Definieer de keys die in de tekst vervangen kunnen worden. Handig voor
    # zaken die vaker terugkomen en bijvoorbeeld aangepast moeten worden voor
    # een volgende editie.
    myst_substitutions:
      thema: "boeken"
      thema_beschrijving: |
        Kies een boek dat je de afgelopen tijd hebt gelezen (voor school of voor je eigen plezier (of allebei)) en maak een creatieve, interactieve versie van de omslag. Zie hier een voorbeeld op basis van *Under the Whispering Door* van TJ Klune, met de originele omslag links en een interactieve adaptatie in Processing aan de rechterkant:

        ![Voorbeeld van een interactieve boekomslag waar huizen uit de lucht vallen en op elkaar gestapeld worden.](assets/demo.gif)

        Mocht je de laatste tijd alleen serieuze literatuur met oersaaie omslagen gelezen hebben, neem dan je favoriete kinderboek als inspiratie. Daar gebeurt vast genoeg op de omslag om iets van te kunnen maken!
      deadline: "donderdag 18 januari, 16:00"
      deadline_uitstel_aanvragen: "maandag 8 januari, 16:00"
      deadline_uitstel: "dinsdag 20 februari, 16:00"
      docent: "Arthur Rump"
      docent_email: "a.rump apenstaartje quadraam punt nl"


# html, repository en launch_buttons instellingen worden globaal voor alle
# syllabi afgehandeld.
